### ISSUE TITLE
background filter stopped working

### ISSUE THREAD

**Issue by chalkos** [Critical-Impact/InventoryTools#100]
My background filter stopped working in one of the last updates.

To start from a clean slate, I disabled the plugin, cleared all my configs, enabled it, then navigated through all the inventories to fill in all the info about the items I have, went to the filters settings and added the duplicated items filter, then went to general settings and selected the duplicated filter as "active background filter".

but neither items nor retainer names got highlighted.

To check if the filter works, i set it as active window filter. and it worked. main window open highlights items and retainer names, but once i close it (with the background filter still set to the duplicated items filter) items and retainer names return to their unmodded state

is there anything else I can config or is this really an issue with the background filter?

**Comment by Critical-Impact** [comment]
Fixed in #95 
Will be in next test version

Background filters should again work like they were before but with the addition of the new windows if any window that can use a UI filter is active, the background filter will be disabled.
This means that if the filters, filter or craft windows are open the background filter won't disable.

I do have plans for an option to allow for background filters to take precedence over UI filters via a setting in the future.

**Comment by chalkos** [comment]
It's working on my side as well. Thanks!
